// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: test_grpc.proto

#include "test_grpc.pb.h"
#include "test_grpc.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/method_handler_impl.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace test_grpc {

static const char* TestGRpc_method_names[] = {
  "/test_grpc.TestGRpc/Put",
};

std::unique_ptr< TestGRpc::Stub> TestGRpc::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< TestGRpc::Stub> stub(new TestGRpc::Stub(channel));
  return stub;
}

TestGRpc::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_Put_(TestGRpc_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status TestGRpc::Stub::Put(::grpc::ClientContext* context, const ::test_grpc::PutRequest& request, ::test_grpc::PutReply* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_Put_, context, request, response);
}

void TestGRpc::Stub::experimental_async::Put(::grpc::ClientContext* context, const ::test_grpc::PutRequest* request, ::test_grpc::PutReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_Put_, context, request, response, std::move(f));
}

void TestGRpc::Stub::experimental_async::Put(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::test_grpc::PutReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_Put_, context, request, response, std::move(f));
}

void TestGRpc::Stub::experimental_async::Put(::grpc::ClientContext* context, const ::test_grpc::PutRequest* request, ::test_grpc::PutReply* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_Put_, context, request, response, reactor);
}

void TestGRpc::Stub::experimental_async::Put(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::test_grpc::PutReply* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_Put_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::test_grpc::PutReply>* TestGRpc::Stub::AsyncPutRaw(::grpc::ClientContext* context, const ::test_grpc::PutRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::test_grpc::PutReply>::Create(channel_.get(), cq, rpcmethod_Put_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::test_grpc::PutReply>* TestGRpc::Stub::PrepareAsyncPutRaw(::grpc::ClientContext* context, const ::test_grpc::PutRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::test_grpc::PutReply>::Create(channel_.get(), cq, rpcmethod_Put_, context, request, false);
}

TestGRpc::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      TestGRpc_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< TestGRpc::Service, ::test_grpc::PutRequest, ::test_grpc::PutReply>(
          std::mem_fn(&TestGRpc::Service::Put), this)));
}

TestGRpc::Service::~Service() {
}

::grpc::Status TestGRpc::Service::Put(::grpc::ServerContext* context, const ::test_grpc::PutRequest* request, ::test_grpc::PutReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace test_grpc

