// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: os_rpc.proto
#ifndef GRPC_os_5frpc_2eproto__INCLUDED
#define GRPC_os_5frpc_2eproto__INCLUDED

#include "os_rpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/method_handler_impl.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace grpc_impl {
class CompletionQueue;
class ServerCompletionQueue;
class ServerContext;
}  // namespace grpc_impl

namespace grpc {
namespace experimental {
template <typename RequestT, typename ResponseT>
class MessageAllocator;
}  // namespace experimental
}  // namespace grpc

namespace osrpc {

// The greeting service definition.
class OSRPC final {
 public:
  static constexpr char const* service_full_name() {
    return "osrpc.OSRPC";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    // Sends a greeting
    virtual ::grpc::Status RPCInit(::grpc::ClientContext* context, const ::osrpc::InitRequest& request, ::osrpc::InitReply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::osrpc::InitReply>> AsyncRPCInit(::grpc::ClientContext* context, const ::osrpc::InitRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::osrpc::InitReply>>(AsyncRPCInitRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::osrpc::InitReply>> PrepareAsyncRPCInit(::grpc::ClientContext* context, const ::osrpc::InitRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::osrpc::InitReply>>(PrepareAsyncRPCInitRaw(context, request, cq));
    }
    virtual ::grpc::Status RPCOpen(::grpc::ClientContext* context, const ::osrpc::OpenRequest& request, ::osrpc::OpenReply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::osrpc::OpenReply>> AsyncRPCOpen(::grpc::ClientContext* context, const ::osrpc::OpenRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::osrpc::OpenReply>>(AsyncRPCOpenRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::osrpc::OpenReply>> PrepareAsyncRPCOpen(::grpc::ClientContext* context, const ::osrpc::OpenRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::osrpc::OpenReply>>(PrepareAsyncRPCOpenRaw(context, request, cq));
    }
    class experimental_async_interface {
     public:
      virtual ~experimental_async_interface() {}
      // Sends a greeting
      virtual void RPCInit(::grpc::ClientContext* context, const ::osrpc::InitRequest* request, ::osrpc::InitReply* response, std::function<void(::grpc::Status)>) = 0;
      virtual void RPCInit(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::osrpc::InitReply* response, std::function<void(::grpc::Status)>) = 0;
      virtual void RPCInit(::grpc::ClientContext* context, const ::osrpc::InitRequest* request, ::osrpc::InitReply* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      virtual void RPCInit(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::osrpc::InitReply* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      virtual void RPCOpen(::grpc::ClientContext* context, const ::osrpc::OpenRequest* request, ::osrpc::OpenReply* response, std::function<void(::grpc::Status)>) = 0;
      virtual void RPCOpen(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::osrpc::OpenReply* response, std::function<void(::grpc::Status)>) = 0;
      virtual void RPCOpen(::grpc::ClientContext* context, const ::osrpc::OpenRequest* request, ::osrpc::OpenReply* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      virtual void RPCOpen(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::osrpc::OpenReply* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
    };
    virtual class experimental_async_interface* experimental_async() { return nullptr; }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::osrpc::InitReply>* AsyncRPCInitRaw(::grpc::ClientContext* context, const ::osrpc::InitRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::osrpc::InitReply>* PrepareAsyncRPCInitRaw(::grpc::ClientContext* context, const ::osrpc::InitRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::osrpc::OpenReply>* AsyncRPCOpenRaw(::grpc::ClientContext* context, const ::osrpc::OpenRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::osrpc::OpenReply>* PrepareAsyncRPCOpenRaw(::grpc::ClientContext* context, const ::osrpc::OpenRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status RPCInit(::grpc::ClientContext* context, const ::osrpc::InitRequest& request, ::osrpc::InitReply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::osrpc::InitReply>> AsyncRPCInit(::grpc::ClientContext* context, const ::osrpc::InitRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::osrpc::InitReply>>(AsyncRPCInitRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::osrpc::InitReply>> PrepareAsyncRPCInit(::grpc::ClientContext* context, const ::osrpc::InitRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::osrpc::InitReply>>(PrepareAsyncRPCInitRaw(context, request, cq));
    }
    ::grpc::Status RPCOpen(::grpc::ClientContext* context, const ::osrpc::OpenRequest& request, ::osrpc::OpenReply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::osrpc::OpenReply>> AsyncRPCOpen(::grpc::ClientContext* context, const ::osrpc::OpenRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::osrpc::OpenReply>>(AsyncRPCOpenRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::osrpc::OpenReply>> PrepareAsyncRPCOpen(::grpc::ClientContext* context, const ::osrpc::OpenRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::osrpc::OpenReply>>(PrepareAsyncRPCOpenRaw(context, request, cq));
    }
    class experimental_async final :
      public StubInterface::experimental_async_interface {
     public:
      void RPCInit(::grpc::ClientContext* context, const ::osrpc::InitRequest* request, ::osrpc::InitReply* response, std::function<void(::grpc::Status)>) override;
      void RPCInit(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::osrpc::InitReply* response, std::function<void(::grpc::Status)>) override;
      void RPCInit(::grpc::ClientContext* context, const ::osrpc::InitRequest* request, ::osrpc::InitReply* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      void RPCInit(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::osrpc::InitReply* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      void RPCOpen(::grpc::ClientContext* context, const ::osrpc::OpenRequest* request, ::osrpc::OpenReply* response, std::function<void(::grpc::Status)>) override;
      void RPCOpen(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::osrpc::OpenReply* response, std::function<void(::grpc::Status)>) override;
      void RPCOpen(::grpc::ClientContext* context, const ::osrpc::OpenRequest* request, ::osrpc::OpenReply* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      void RPCOpen(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::osrpc::OpenReply* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit experimental_async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class experimental_async_interface* experimental_async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class experimental_async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::osrpc::InitReply>* AsyncRPCInitRaw(::grpc::ClientContext* context, const ::osrpc::InitRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::osrpc::InitReply>* PrepareAsyncRPCInitRaw(::grpc::ClientContext* context, const ::osrpc::InitRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::osrpc::OpenReply>* AsyncRPCOpenRaw(::grpc::ClientContext* context, const ::osrpc::OpenRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::osrpc::OpenReply>* PrepareAsyncRPCOpenRaw(::grpc::ClientContext* context, const ::osrpc::OpenRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_RPCInit_;
    const ::grpc::internal::RpcMethod rpcmethod_RPCOpen_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    // Sends a greeting
    virtual ::grpc::Status RPCInit(::grpc::ServerContext* context, const ::osrpc::InitRequest* request, ::osrpc::InitReply* response);
    virtual ::grpc::Status RPCOpen(::grpc::ServerContext* context, const ::osrpc::OpenRequest* request, ::osrpc::OpenReply* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_RPCInit : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_RPCInit() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_RPCInit() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RPCInit(::grpc::ServerContext* context, const ::osrpc::InitRequest* request, ::osrpc::InitReply* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestRPCInit(::grpc::ServerContext* context, ::osrpc::InitRequest* request, ::grpc::ServerAsyncResponseWriter< ::osrpc::InitReply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_RPCOpen : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_RPCOpen() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_RPCOpen() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RPCOpen(::grpc::ServerContext* context, const ::osrpc::OpenRequest* request, ::osrpc::OpenReply* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestRPCOpen(::grpc::ServerContext* context, ::osrpc::OpenRequest* request, ::grpc::ServerAsyncResponseWriter< ::osrpc::OpenReply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_RPCInit<WithAsyncMethod_RPCOpen<Service > > AsyncService;
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_RPCInit : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    ExperimentalWithCallbackMethod_RPCInit() {
      ::grpc::Service::experimental().MarkMethodCallback(0,
        new ::grpc::internal::CallbackUnaryHandler< ::osrpc::InitRequest, ::osrpc::InitReply>(
          [this](::grpc::ServerContext* context,
                 const ::osrpc::InitRequest* request,
                 ::osrpc::InitReply* response,
                 ::grpc::experimental::ServerCallbackRpcController* controller) {
                   return this->RPCInit(context, request, response, controller);
                 }));
    }
    void SetMessageAllocatorFor_RPCInit(
        ::grpc::experimental::MessageAllocator< ::osrpc::InitRequest, ::osrpc::InitReply>* allocator) {
      static_cast<::grpc::internal::CallbackUnaryHandler< ::osrpc::InitRequest, ::osrpc::InitReply>*>(
          ::grpc::Service::experimental().GetHandler(0))
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_RPCInit() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RPCInit(::grpc::ServerContext* context, const ::osrpc::InitRequest* request, ::osrpc::InitReply* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual void RPCInit(::grpc::ServerContext* context, const ::osrpc::InitRequest* request, ::osrpc::InitReply* response, ::grpc::experimental::ServerCallbackRpcController* controller) { controller->Finish(::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "")); }
  };
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_RPCOpen : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    ExperimentalWithCallbackMethod_RPCOpen() {
      ::grpc::Service::experimental().MarkMethodCallback(1,
        new ::grpc::internal::CallbackUnaryHandler< ::osrpc::OpenRequest, ::osrpc::OpenReply>(
          [this](::grpc::ServerContext* context,
                 const ::osrpc::OpenRequest* request,
                 ::osrpc::OpenReply* response,
                 ::grpc::experimental::ServerCallbackRpcController* controller) {
                   return this->RPCOpen(context, request, response, controller);
                 }));
    }
    void SetMessageAllocatorFor_RPCOpen(
        ::grpc::experimental::MessageAllocator< ::osrpc::OpenRequest, ::osrpc::OpenReply>* allocator) {
      static_cast<::grpc::internal::CallbackUnaryHandler< ::osrpc::OpenRequest, ::osrpc::OpenReply>*>(
          ::grpc::Service::experimental().GetHandler(1))
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_RPCOpen() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RPCOpen(::grpc::ServerContext* context, const ::osrpc::OpenRequest* request, ::osrpc::OpenReply* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual void RPCOpen(::grpc::ServerContext* context, const ::osrpc::OpenRequest* request, ::osrpc::OpenReply* response, ::grpc::experimental::ServerCallbackRpcController* controller) { controller->Finish(::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "")); }
  };
  typedef ExperimentalWithCallbackMethod_RPCInit<ExperimentalWithCallbackMethod_RPCOpen<Service > > ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_RPCInit : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_RPCInit() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_RPCInit() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RPCInit(::grpc::ServerContext* context, const ::osrpc::InitRequest* request, ::osrpc::InitReply* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_RPCOpen : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_RPCOpen() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_RPCOpen() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RPCOpen(::grpc::ServerContext* context, const ::osrpc::OpenRequest* request, ::osrpc::OpenReply* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_RPCInit : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithRawMethod_RPCInit() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_RPCInit() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RPCInit(::grpc::ServerContext* context, const ::osrpc::InitRequest* request, ::osrpc::InitReply* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestRPCInit(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_RPCOpen : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithRawMethod_RPCOpen() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_RPCOpen() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RPCOpen(::grpc::ServerContext* context, const ::osrpc::OpenRequest* request, ::osrpc::OpenReply* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestRPCOpen(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_RPCInit : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    ExperimentalWithRawCallbackMethod_RPCInit() {
      ::grpc::Service::experimental().MarkMethodRawCallback(0,
        new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
          [this](::grpc::ServerContext* context,
                 const ::grpc::ByteBuffer* request,
                 ::grpc::ByteBuffer* response,
                 ::grpc::experimental::ServerCallbackRpcController* controller) {
                   this->RPCInit(context, request, response, controller);
                 }));
    }
    ~ExperimentalWithRawCallbackMethod_RPCInit() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RPCInit(::grpc::ServerContext* context, const ::osrpc::InitRequest* request, ::osrpc::InitReply* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual void RPCInit(::grpc::ServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response, ::grpc::experimental::ServerCallbackRpcController* controller) { controller->Finish(::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "")); }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_RPCOpen : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    ExperimentalWithRawCallbackMethod_RPCOpen() {
      ::grpc::Service::experimental().MarkMethodRawCallback(1,
        new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
          [this](::grpc::ServerContext* context,
                 const ::grpc::ByteBuffer* request,
                 ::grpc::ByteBuffer* response,
                 ::grpc::experimental::ServerCallbackRpcController* controller) {
                   this->RPCOpen(context, request, response, controller);
                 }));
    }
    ~ExperimentalWithRawCallbackMethod_RPCOpen() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RPCOpen(::grpc::ServerContext* context, const ::osrpc::OpenRequest* request, ::osrpc::OpenReply* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual void RPCOpen(::grpc::ServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response, ::grpc::experimental::ServerCallbackRpcController* controller) { controller->Finish(::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "")); }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_RPCInit : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithStreamedUnaryMethod_RPCInit() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler< ::osrpc::InitRequest, ::osrpc::InitReply>(std::bind(&WithStreamedUnaryMethod_RPCInit<BaseClass>::StreamedRPCInit, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_RPCInit() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status RPCInit(::grpc::ServerContext* context, const ::osrpc::InitRequest* request, ::osrpc::InitReply* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedRPCInit(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::osrpc::InitRequest,::osrpc::InitReply>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_RPCOpen : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithStreamedUnaryMethod_RPCOpen() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler< ::osrpc::OpenRequest, ::osrpc::OpenReply>(std::bind(&WithStreamedUnaryMethod_RPCOpen<BaseClass>::StreamedRPCOpen, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_RPCOpen() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status RPCOpen(::grpc::ServerContext* context, const ::osrpc::OpenRequest* request, ::osrpc::OpenReply* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedRPCOpen(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::osrpc::OpenRequest,::osrpc::OpenReply>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_RPCInit<WithStreamedUnaryMethod_RPCOpen<Service > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_RPCInit<WithStreamedUnaryMethod_RPCOpen<Service > > StreamedService;
};

}  // namespace osrpc


#endif  // GRPC_os_5frpc_2eproto__INCLUDED
